In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("results/experiment_result.csv")
df.head()

         model  precision  recall      f1
0  gpt_oss_20b     0.8669  0.8709  0.8689
1  gpt_oss_20b     0.8406  0.8599  0.8502
2  gpt_oss_20b     0.8511  0.8519  0.8515
3    qwen3_32b     0.8866  0.8312  0.8580
4    qwen3_32b     0.8998  0.8346  0.8660

In [15]:
# compute average and std group by model column
result_df = df.groupby("model").agg(["mean", "std"]).reset_index()
result_df.head(10)

                   model precision              recall                  f1  \
                              mean       std      mean       std      mean
0            gpt_oss_20b  0.852867  0.013239  0.860900  0.009539  0.856867
1           meditron_70b  0.411900  0.158250  0.027450  0.018738  0.051250
2  openbiollm_llama3_70b  0.593900  0.009180  0.536100  0.008240  0.563533
3              qwen3_32b  0.895800  0.007990  0.835967  0.005577  0.864833


        std
0  0.010441
1  0.034295
2  0.007650
3  0.006331