In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("results/experiment_result.csv")
df.head()

,model,true_negative,false_positive,false_negative,true_positive,non-medical_precision,non-medical_recall,non-medical_f1-score,non-medical_support,medical_precision,...,medical_support,accuracy,macro_avg_precision,macro_avg_recall,macro_avg_f1-score,macro_avg_support,weighted_avg_precision,weighted_avg_recall,weighted_avg_f1-score,weighted_avg_support
0,gpt_oss_20b,642,33,23,651,0.965414,0.951111,0.958209,675.0,0.951754,...,674.0,0.958488,0.958584,0.958493,0.958486,1349.0,0.958589,0.958488,0.958486,1349.0
1,gpt_oss_20b,651,24,21,652,0.968750,0.964444,0.966592,675.0,0.964497,...,673.0,0.966617,0.966624,0.966620,0.966617,1348.0,0.966627,0.966617,0.966617,1348.0
2,gpt_oss_20b,642,33,21,652,0.968326,0.951111,0.959641,675.0,0.951825,...,673.0,0.959941,0.960075,0.959954,0.959938,1348.0,0.960088,0.959941,0.959938,1348.0
3,qwen3_32b,38,637,3,670,0.926829,0.056296,0.106145,675.0,0.512624,...,673.0,0.525223,0.719727,0.525919,0.391456,1348.0,0.720034,0.525223,0.391033,1348.0
4,qwen3_32b,30,645,3,670,0.909091,0.044444,0.084746,675.0,0.509506,...,673.0,0.519288,0.709298,0.519993,0.379395,1348.0,0.709595,0.519288,0.378958,1348.0

In [9]:
# compute average and std group by model column
result_df = df.groupby("model").agg(["mean", "std"]).reset_index()

result_df[["model", "non-medical_recall", "non-medical_precision", "non-medical_f1-score", "accuracy"]].head()

                   model non-medical_recall           non-medical_precision  \
                                       mean       std                  mean
0            gpt_oss_20b           0.955556  0.007698              0.967496
1           meditron_70b           0.225185  0.009715              0.455840
2  openbiollm_llama3_70b           0.982716  0.001711              0.701132
3              qwen3_32b           0.045432  0.010406              0.931973

            non-medical_f1-score            accuracy
        std                 mean       std      mean       std
0  0.001816             0.961481  0.004484  0.961682  0.004335
1  0.029690             0.301336  0.013751  0.477003  0.015543
2  0.014345             0.818333  0.010404  0.781405  0.015009
3  0.025841             0.086487  0.018847  0.520277  0.004533